# Generated by Django 5.2.16 on 2026-07-22 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mois_index', models.PositiveSmallIntegerField(help_text='1 = septembre … 9 = mai')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('saisi_le', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='cycles.cycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='members.member')),
            ],
            options={
                'ordering': ['member__nom', 'mois_index'],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'member', 'mois_index'), name='depot_unique_par_mois')],
            },
        ),
    ]
