# Generated by Django 5.2.16 on 2026-07-22 12:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(help_text='Ex. « 2025-2026 »', max_length=40)),
                ('mois_debut', models.PositiveSmallIntegerField(default=9, help_text='9 = septembre')),
                ('duree_depot', models.PositiveSmallIntegerField(default=9, help_text='Nb de mois de dépôt')),
                ('mois_delai', models.PositiveSmallIntegerField(default=12, help_text='Délai de remboursement')),
                ('taux_epargne', models.DecimalField(decimal_places=3, default=Decimal('0.05'), max_digits=4)),
                ('taux_majoration', models.DecimalField(decimal_places=3, default=Decimal('0.05'), max_digits=4)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('cloture', 'Clôturé')], default='ouvert', max_length=10)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='cycles.caisse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('caisse', 'libelle'), name='cycle_unique_par_caisse')],
            },
        ),
    ]
