# Generated by Django 5.2.16 on 2026-07-22 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mois_pret', models.PositiveSmallIntegerField(help_text='Mois du prêt (1 = septembre … 9 = mai)')),
                ('mois_remboursement', models.PositiveSmallIntegerField(blank=True, help_text='Vide = remboursé au délai (août)', null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='cycles.cycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='members.member')),
            ],
            options={
                'ordering': ['member__nom', 'mois_pret'],
            },
        ),
    ]
