# Generated by Django 5.2.16 on 2026-07-22 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='cycles.caisse')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
